name: Release
on:
  push:
    branches:
      - main
      - cristian-a3
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FRONTEND: app-frontend
  IMAGE_NAME_SERVICE: app-service

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push multi-platform Docker image
        run: |
          IMG="ghcr.io/${{ github.repository }}"
          IMG=${IMG@L}
          echo "Final image name: $IMG"

          # Build and push latest tag for multiple platforms
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t $IMG:latest \
            --push .

          # If this is a tag push, also build and push that version tag
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            docker buildx build --platform linux/amd64,linux/arm64 \
              -t $IMG:$VERSION \
              --push .
          fi
