name: Build and Release

on:
  push:
    branches:
      - main
      - cristian-release-prerelease
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-pre*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_FRONTEND: app-frontend
  IMAGE_NAME_SERVICE: app-service

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Determine release version
        id: version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Build and push frontend image
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_FRONTEND }}"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          VERSION="${{ steps.version.outputs.version }}"

          docker buildx build --platform linux/amd64,linux/arm64 \
            -f Dockerfile.frontend \
            -t $IMAGE:latest \
            -t $IMAGE:$VERSION \
            --push .

      - name: Build and push service image
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_SERVICE }}"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          VERSION="${{ steps.version.outputs.version }}"

          docker buildx build --platform linux/amd64,linux/arm64 \
            -f Dockerfile.service \
            -t $IMAGE:latest \
            -t $IMAGE:$VERSION \
            --push .

      - name: Create GitHub Release (if tagged)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          prerelease: ${{ contains(github.ref_name, '-pre') }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Docker Images

            - `${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_FRONTEND }}:${{ steps.version.outputs.version }}`
            - `${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_SERVICE }}:${{ steps.version.outputs.version }}`

            ## Pull example

            ```bash
            docker pull ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_SERVICE }}:${{ steps.version.outputs.version }}
            ```

